# Generated by Django 4.2.7 on 2025-11-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bughunterjob',
            name='code_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bughunterjob',
            name='language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
